# Generated by Django 4.1 on 2022-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('phone', 'phone'), ('laptop', 'laptop'), ('tablet', 'tablet')], max_length=256)),
            ],
        ),
    ]
