# Generated by Django 4.1 on 2022-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpdeskContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=512)),
                ('text', models.TextField()),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
